employee/urls.py
from django.conf.urls import url

from .views import (
    AddEmployeeView,
    AllEmployeesView,
    EmployeeDetailView,
    EmployeeUpdateView,
    SalaryUpdateView,
    EmployeeDeleteView,
    AllRelationsView,
    AddRelationView,
    UpdateRelationView,
    DeleteRelationView,
)

urlpatterns = [
    url(r'^add/$', AddEmployeeView.as_view(), name='add'),
    url(r'^$', AllEmployeesView.as_view(), name='all'),
    url(r'^(?P<pk>\d+)/$', EmployeeDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update/$', EmployeeUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/update_salary/$', SalaryUpdateView.as_view(), name='update-salary'),
    url(r'^(?P<pk>\d+)/delete/$', EmployeeDeleteView.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/relations/$', AllRelationsView.as_view(), name='all-relations'),
    url(r'^(?P<pk>\d+)/add_relation/$', AddRelationView.as_view(), name='add-relation'),
    url(r'^(?P<pk>\d+)/update_relation/$', UpdateRelationView.as_view(), name='update-relation'),
    url(r'^(?P<pk>\d+)/delete_relation/$', DeleteRelationView.as_view(), name='delete-relation'),
]

web_interface/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from employee import views as employee_views
from user import views as user_view
from main_website import views as main_view

urlpatterns = [
    path('', main_view.home, name="home"),
    path('register/',user_view.register, name='register'),
    path('profile/',user_view.profile, name='profile'),
    path('admin/', admin.site.urls),
    path('formular/', include('formular.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('adeverinte/', include('adeverinte.urls')),
    path('about/', main_view.about, name='about'),
    path('employees/', include(('employee.urls', 'employees'), namespace='employees')),
    path('default_tmpl/', include(('default_tmpl.urls', 'default_tmpl'), namespace='default_tmpl')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_website/models.py
from django.db import models

from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    data_publish = models.DateField(default=timezone.now)
    time_publish = models.TimeField(default=timezone.now)

    def __str__(self):
        return self.title

main_website/views.py
from django.shortcuts import render

#Change path to parent directory for aneasier acces to files
import os,sys,inspect
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0,parentdir)

from statistici.models import Statistici
from main_website.models import Post

def home(request):
	context = {
		'posts':Post.objects.all(),
		'statistici':Statistici.objects.get(id=1)
	}
	return render(request, 'main_website/home.html', context)

def about(request):
	return render(request, 'main_website/about.html')

main_website/templates/main_website/about.html
{% extends "main_website/base.html" %}
{% block content %}
<p>
  &nbsp;&nbsp;&nbsp;&nbsp;Ideea generală a acestui proiect este de a exporta adeverinte în diferite tipuri de format. Ca și format v-om putea exporta adeverințe în PDF sau word iar adeverințele respective vor fi exportate din interfața web. Pentru interfața web vom face un sistem de autentificare astfel diferiti useri vor putea avea diferite permisiuni în funcție de tipul user ului. Vom porni de la un sistem de autentificare cu user și parolă, iar pe baza user lui și parolei se va identifica tipul de user și se încarcă o platformă aferentă tipului de user. Vor exista trei tipuri de user utilizator master utilizator administrator și utilizator final. Pentru utilizatorul master vom putea și vom avea acces la absolut toate serviciile oferite de această platformă inclusiv la o platformă care seteaza si administreaza noutăți de fapt aceasta va fi diferența principală între un utilizator Master și un utilizator administrator. Pentru un utilizator administrator vom avea dreptul de a creat template-uri, de a crea utilizatori finali, de a seta contul aferent business și de a exporta documente și adeverințe. Iar pentru un utilizator final dreptul acestuia este de a exporta doar adeverințe create de utilizatorul administratorul al utilizatorului final. Utilizatorul Master va avea posibilitatea de a crea template uri globale însemnând că aceste template uri vor putea și vor fi primele templeuri afișate în momentul în care se creează un cont business administrat de către un utilizator administrator.

</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;Scopul final al acestui proiect este de a genera documente și a adeverinte necesare în procesul de resurse umane pentru fiecare angajat în parte în mod automat astfel nu vor mai fi necesare vizitele la departamentul de resurse umane întrucât fiecare angajat va avea un cont de unde va putea exporta adeverința sau documentul necesar, în acest caz vom considera utilizatorul final ca fiind un angajat al unei companii iar administratorul va fi o persoană desemnată din partea departamentului de resurse umane pentru a administra toate documentele și adeverințile inclusiv și templete-urile pentru pentru generarea acestora. Vom avea în vedere în crearea platformei o interfață cât mai ușor de utilizat cât și să fie intuitivă pentru fiecare utilizator în parte
</p>
{% endblock content %}

main_website/templates/main_website/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'main_website/main.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="{% static 'main_website/dropdown-btn.js' %}"></script>

	{% if title %}
		<title>{{ title }}</title>>
	{% else %}
		<title>Exportator Adeverinte</title>
	{% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-orange fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'home' %}">Adeverinte</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'profile' %}">Profilul meu</a>
                  <a class="nav-item nav-link" href="{% url 'logout' %}">Deconectare</a>
              {% else %}
                  <a class="nav-item nav-link" href="{% url 'login' %}">Conecteaza-te</a>
                  <a class="nav-item nav-link" href="{% url 'register' %}">Creeaza cont</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
          <div class="col-md-3">
              <div class="sidenav">
                {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'adeverinte-home' %}">Acasa</a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'home' %}">Acasa</a>
                {% endif %}
                  {% if user.is_authenticated %}
                      <a class="nav-item nav-link" href="{% url 'employees:all' %}">Administrare conturi</a>
                      <a class="nav-item nav-link" href="{% url 'default_tmpl:home' %}">Administrare template</a>
                      <a class="nav-item nav-link" href="{% url 'home' %}">Mesaje useri</a>
                      <a class="nav-item nav-link" href="{% url 'home' %}">Setari Cont</a>
                  {% endif %}
                  <a class="nav-item nav-link" href="{% url 'about' %}">Despre Adeverinte</a>
              </div>
          </div>
        <div class="col-md-6">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}<h1>Continutul lipseste!</h1>{% endblock %}
        </div>
        <div class="col-md-3">
          <div class="content-section sidebar">
            <h3>Statistici</h3>
            {% block statistici %}
              <p class='text-muted'>Statistici la nivel global.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Numa solicitari exportate: XX</li>
                  <li class="list-group-item list-group-item-light">Numar companii inregistrate: XX</li>
                  <li class="list-group-item list-group-item-light">Numar template-uri adeverinte: XX</li>
                </ul>
              </p>
            {% endblock %}
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

main_website/templates/main_website/base_statistici.html
{% extends "main_website/base.html" %}
{% block statistici %}
  <p class='text-muted'>Statistici la nivel global.
    <ul class="list-group">
      <li class="list-group-item list-group-item-light">Numa solicitari exportate: {{ statistici.number_of_documents }}</li>
      <li class="list-group-item list-group-item-light">Numar companii inregistrate: {{ statistici.number_of_users }}</li>
      <li class="list-group-item list-group-item-light">Numar template-uri adeverinte: {{ statistici.number_of_templates }}</li>
    </ul>
  </p>
{% endblock statistici %}

main_website/templates/main_website/home.html
{% extends "main_website/base_statistici.html" %}
{% block content %}
{% if user.is_authenticated %}
    {% for post in posts %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.data_publish|date:"F d, Y" }}</a>
              <small class="text-muted">{{ post.time_publish|time:"G:i" }}</small>
            </div>
            <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
{% else %}
  <p>
  &nbsp;&nbsp;&nbsp;&nbsp;În alegerea obiectivului acestui proiect am luat în considerare problemele care au fost în jurul meu și rezolvarea acestora cu ajutorul tehnologiei curente.In mod special mi a atras atentia departamentul de resurse umane care utilizează o grămadă de documente prin urmare și hârtie care nu este un aspect tocmai ecologic, în plus în afară de acest lucru distribuirea adeverințelor și documentelor necesare oricărui proces de resurse umane este un cost și un și un timp total neproductivă pentru orice angajat al departamentului de resurse umane timp care ar putea fi utilizat în celelalte procese de management al angajaților.
  </p>

  <p>
  &nbsp;&nbsp;&nbsp;&nbsp;Totodată utilizatorul principal al acestui proiect sunt firmele/societăților comerciale cu un număr limitat de angajati care nu își pot permite un departament de resurse umane abilitat și prin urmare administrarea acestor documente si adeverinte ar fi un stes și un cost suplimentar ne necesar. Tocmai de aceea din contul administratorului este posibilă exportarea și generarea de documente word sau PDF pentru fiecare angajat al societății în cazul în care nu se dorește generarea de user și fiecare user să se logheze separat deși este posibil ca utilizatorul final să se logheze separat pentru a genera orice document necesar. Astăzi putem spune că avem o platformă care administrează atât generarea de documente cât și generarea de user pentru a avea acces la documentele aferente.
  </p>

  <p>
  &nbsp;&nbsp;&nbsp;&nbsp;Problema identificată a fost crearea de documente aferente procesului de resurse umane în mod manual și timpul enorm de mare necesar în modificarea și distribuirea acestora atât pentru societățile mici ca și dimensiune cât și pentru societățile mari și care doresc să  își automatizeze procesele de resurse umane necesare prelucrării de documente și adeverințe prin urmare putem spune că platforma se adresează unui grup țintă oricare societate comercială indiferent de numărul de angajați.
  </p>
  {%endif%}

{% endblock content %}