employee/urls.py
from django.conf.urls import url

from .views import (
    AddEmployeeView,
    AllEmployeesView,
    EmployeeDetailView,
    EmployeeUpdateView,
    SalaryUpdateView,
    EmployeeDeleteView,
    AllRelationsView,
    AddRelationView,
    UpdateRelationView,
    DeleteRelationView,
)

urlpatterns = [
    url(r'^add/$', AddEmployeeView.as_view(), name='add'),
    url(r'^$', AllEmployeesView.as_view(), name='all'),
    url(r'^(?P<pk>\d+)/$', EmployeeDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update/$', EmployeeUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/update_salary/$', SalaryUpdateView.as_view(), name='update-salary'),
    url(r'^(?P<pk>\d+)/delete/$', EmployeeDeleteView.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/relations/$', AllRelationsView.as_view(), name='all-relations'),
    url(r'^(?P<pk>\d+)/add_relation/$', AddRelationView.as_view(), name='add-relation'),
    url(r'^(?P<pk>\d+)/update_relation/$', UpdateRelationView.as_view(), name='update-relation'),
    url(r'^(?P<pk>\d+)/delete_relation/$', DeleteRelationView.as_view(), name='delete-relation'),
]

web_interface/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from employee import views as employee_views
from user import views as user_view
from main_website import views as main_view

urlpatterns = [
    path('', main_view.home, name="home"),
    path('register/',user_view.register, name='register'),
    path('profile/',user_view.profile, name='profile'),
    path('admin/', admin.site.urls),
    path('formular/', include('formular.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('adeverinte/', include('adeverinte.urls')),
    path('about/', main_view.about, name='about'),
    path('employees/', include(('employee.urls', 'employees'), namespace='employees')),
    path('default_tmpl/', include(('default_tmpl.urls', 'default_tmpl'), namespace='default_tmpl')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import post_save


class Employees(models.Model):
    GENDER_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
    ]
    Position_CHOICES = [
        ('Employee', 'Employee'),
        ('Manager', 'Manager'),
        ('CEO', 'CEO'),
    ]
    MARITAL_STATUS_CHOICES = [
        ('Single', 'Single'),
        ('Married', 'Married'),
    ]
    first_name = models.CharField(max_length=255)
    middle_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    full_name = models.CharField(max_length=500)
    national_identifier = models.BigIntegerField()
    age = models.PositiveIntegerField()
    gender = models.CharField(choices=GENDER_CHOICES, max_length=25)
    date_of_birth = models.DateField()
    place_of_birth = models.CharField(max_length=255)
    position = models.CharField(choices=Position_CHOICES, max_length=25)
    job = models.CharField(max_length=255, null=True)
    country = models.CharField(max_length=255)
    nationality = models.CharField(max_length=255)
    marital_status = models.CharField(choices=MARITAL_STATUS_CHOICES, max_length=25)
    salary = models.PositiveIntegerField()
    deduction = models.PositiveIntegerField(default=0, null=True)
    earning = models.PositiveIntegerField(default=0, null=True)
    deduction_description = models.TextField(null=True)
    earning_description = models.TextField(null=True)
    activated = models.BooleanField(default=True)
    freeze = models.BooleanField(default=False)
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.full_name

    def get_absolute_url(self):
        return reverse('employees:detail', kwargs={'pk': self.pk})


class Relationship(models.Model):
    RELATIONSHIP_TYPE_CHOICES = [
        ('wife', 'Wife'),
        ('child', 'Child'),
        ('husband', 'Husband'),
    ]
    employee = models.ForeignKey(Employees, on_delete=models.CASCADE)
    relationship_type = models.CharField(choices=RELATIONSHIP_TYPE_CHOICES, max_length=25)
    name = models.CharField(max_length=255)
    age = models.PositiveIntegerField()
    date_of_birth = models.DateField()
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.relationship_type


def post_save_employee_receiver(sender, instance, created, *args, **kwargs):
    if created:
        qs = Employees.objects.filter(id=instance.id, national_identifier=instance.national_identifier)
        if qs.exists() and qs.count() == 1:
            employee = qs.first()
            position = employee.position
            if position == 'Employee':
                deduction = (employee.salary * 7.5) / 100
                employee.deduction = deduction
                employee.save()
            if position == 'Manager':
                deduction = (employee.salary * 12) / 100
                employee.deduction = deduction
                employee.save()
            if position == 'CEO':
                deduction = (employee.salary * 15) / 100
                employee.deduction = deduction
                employee.save()


post_save.connect(post_save_employee_receiver, sender=Employees)

employee/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
    View,
)
from django.urls import reverse_lazy, reverse
from django.contrib import messages

from .forms import (
    AddEmployeeForm,
    UpdateEmployeeForm,
    AddRelationForm,
    UpdateSalaryForm,
)
from .models import Employees, Relationship


# show all employees
class AllEmployeesView(ListView):
    template_name = 'employees/all_employees.html'
    #template_name = 'employees/all_employees_table.html'

    def get_queryset(self):
        qs = Employees.objects.filter(activated=True).order_by('-id')
        return qs

    def get_context_data(self, **kwargs):
        context = super(AllEmployeesView, self).get_context_data(**kwargs)
        context['title'] = 'All Employees'
        return context


# show employee detail
class EmployeeDetailView(DetailView):
    template_name = 'employees/employee_detail.html'

    def get_queryset(self):
        qs = Employees.objects.filter(id=self.kwargs['pk'], activated=True)
        return qs

    def get_context_data(self, **kwargs):
        context = super(EmployeeDetailView, self).get_context_data(**kwargs)
        context['title'] = 'Employee'
        return context


# add new employee
class AddEmployeeView(CreateView):
    form_class = AddEmployeeForm
    template_name = 'employees/add_new_employee.html'

    def get_context_data(self, **kwargs):
        context = super(AddEmployeeView, self).get_context_data(**kwargs)
        context['title'] = 'Add Employee'
        return context


# update employee information except salary
class EmployeeUpdateView(UpdateView):
    form_class = UpdateEmployeeForm
    model = Employees
    template_name = 'employees/employee_update.html'

    def get_queryset(self):
        qs = Employees.objects.filter(id=self.kwargs['pk'], activated=True, freeze=False)
        return qs

    def get_context_data(self, **kwargs):
        context = super(EmployeeUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Update Employee'
        return context


# update employee salary, deduction and earning
class SalaryUpdateView(UpdateView):
    form_class = UpdateSalaryForm
    model = Employees
    template_name = 'employees/update_employee_salary.html'

    def get_queryset(self):
        qs = Employees.objects.filter(id=self.kwargs['pk'], activated=True, freeze=False)
        return qs

    def get_context_data(self, **kwargs):
        context = super(SalaryUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Update Salary'
        qs = Employees.objects.filter(id=self.kwargs['pk'], activated=True, freeze=False).first()
        context['name'] = qs.full_name
        context['id'] = qs.id
        return context


# delete employee if not connected to a job
class EmployeeDeleteView(DeleteView):
    template_name = 'employees/employee_detail.html'

    def post(self, *args, **kwargs):
        qs = Employees.objects.filter(id=self.kwargs['pk'], freeze=False).first()
        job_status = qs.job
        if job_status is None or job_status == '':
            qs.delete()
            return redirect(reverse('employees:all'))
        else:
            qs.freeze = True
            qs.save()
            messages.error(self.request, 'you can not delete this employee because he has a job')
            return redirect(reverse('employees:all'))


# show all relations for married employees
class AllRelationsView(ListView):
    template_name = 'employees/all_relations.html'

    def get_queryset(self):
        qs = Relationship.objects.filter(employee_id=self.kwargs['pk']).order_by('-id')
        return qs

    def get_context_data(self, **kwargs):
        context = super(AllRelationsView, self).get_context_data(**kwargs)
        context['title'] = 'All Relations'
        context['name'] = Employees.objects.filter(id=self.kwargs['pk']).first().full_name
        context['id'] = Employees.objects.filter(id=self.kwargs['pk']).first().id
        return context


# add relation to married employees
class AddRelationView(View):
    form_class = AddRelationForm
    template_name = 'employees/add_new_relation.html'

    def get(self, request, pk):
        form = self.form_class(None)
        context = {
            'form': form,
            'title': 'Add Relation'
        }
        return render(request, self.template_name, context)

    def post(self, request, pk):
        form = self.form_class(request.POST)
        if form.is_valid():
            qs = Employees.objects.filter(id=pk, activated=True, freeze=False).first()
            relation = Relationship.objects.create(
                employee=qs,
                relationship_type=form.cleaned_data.get('relationship_type'),
                name=form.cleaned_data.get('name'),
                age=form.cleaned_data.get('age'),
                date_of_birth=form.cleaned_data.get('date_of_birth'),
            )
            return redirect(reverse('employees:all-relations', kwargs={'pk': pk}))
        else:
            messages.error(request, 'you can not add relation to this employee')
            context = {
                'form': form,
                'title': 'Add Relation'
            }
            return render(request, self.template_name, context)


# update relation for married employees
class UpdateRelationView(UpdateView):
    form_class = AddRelationForm
    model = Relationship
    template_name = 'employees/update_relation.html'

    def get_success_url(self):
        employee_id = Relationship.objects.filter(id=self.kwargs['pk']).first().employee_id
        return reverse_lazy('employee:all-relations', kwargs={'pk': employee_id})

    def get_queryset(self):
        qs = Relationship.objects.filter(id=self.kwargs['pk'])
        return qs

    def get_context_data(self, **kwargs):
        context = super(UpdateRelationView, self).get_context_data(**kwargs)
        context['title'] = 'Update Relation'
        return context


# delete relation from married employees
class DeleteRelationView(DeleteView):
    queryset = Relationship.objects.all()
    template_name = 'employees/all_relations.html'

    def get_success_url(self):
        employee_id = Relationship.objects.filter(id=self.kwargs['pk']).first().employee_id
        return reverse_lazy('employees:all-relations', kwargs={'pk': employee_id})

employee/templates/employees/add_new_employee.html
{% extends 'main_website/base.html' %}

{% block content %}
    <div class="col-sm-offset-3 col-sm-6">
        <h2 class="text-center"><i class="fa fa-user-plus"></i> Add New Employee</h2>
        <br>
            {#{% if form.errors.non_field_errors %}#}
            {#    {{ form.errors.non_field_errors }}#}
            {#{% endif %}#}

            {#{% if form.errors %}#}
            {#    {{ form.errors }}#}
            {#{% endif %}#}

            {% load crispy_forms_tags %}

            <form method="POST" enctype="multipart/form-data" action="" class="form-group">
                {% csrf_token %}
            {#    {% crispy form %}#}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">{{ title }}</button>
            </form>

            {#{% if form.instance %}#}
            {#    <h1>{{ form.instance }}</h1>#}
            {#{% endif %}#}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    </div>
{% endblock %}

employee/templates/employees/add_new_relation.html
{% extends 'main_website/base.html' %}

{% block content %}
    <div class="col-sm-offset-3 col-sm-6">
        <h2 class="text-center"><i class="fa fa-user-plus"></i> Add New Relation</h2>
        <br>
            {#{% if form.errors.non_field_errors %}#}
            {#    {{ form.errors.non_field_errors }}#}
            {#{% endif %}#}

            {#{% if form.errors %}#}
            {#    {{ form.errors }}#}
            {#{% endif %}#}

            {% load crispy_forms_tags %}

            <form method="POST" enctype="multipart/form-data" action="" class="form-group">
                {% csrf_token %}
            {#    {% crispy form %}#}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">{{ title }}</button>
            </form>

            {#{% if form.instance %}#}
            {#    <h1>{{ form.instance }}</h1>#}
            {#{% endif %}#}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    </div>
{% endblock %}

employee/templates/employees/all_employees.html
{% extends 'main_website/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-sm-6">
              <h3>
                <a href="{% url 'employees:all' %}"><i class="fa fa-users"></i> All Employees</a>
              </h3>
        </div>
        <div class="col-sm-6">
              <h3>
               <a href="{% url 'employees:add' %}"><i class="fa fa-user-plus"></i> Add Employee</a>
              </h3>
            <br>
            <br>
        </div>
        {% for emp in object_list %}
            <div class="col-sm-4">
            <div class="thumbnail">
              <div class="caption">
                  <h4>Full Name : <br><a href="{% url 'employees:detail' emp.id %}">{{ emp.full_name }}</a></h4>
                <p>Age : {{ emp.age }}</p>
                <p>Gender : {{ emp.gender }}</p>
                <p>Place of Birth : {{ emp.place_of_birth }}</p>
                <p>Position : {{ emp.position }}</p>
                <p>Job : {{ emp.job }}</p>
                <p>Marital Status : {{ emp.marital_status }}</p>
                <p>Number of Relations : {{ emp.relationship_set.all.count }}</p>
              {% if emp.freeze == True %}
                  <p class="lead text-center" style="color: #f00; margin-top: 18px;">This employee is frozen</p>
              {% else %}
                <a href="{% url 'employees:update' emp.id %}" class="btn btn-info btn-raised btn-sm">
                    <i class="fa fa-user"></i> Update
                </a>
                <a href="{% url 'employees:update-salary' emp.id %}" class="btn btn-default btn-raised btn-sm">
                    <i class="fa fa-dollar-sign"></i>  Update Salary
                </a>
                <!-- Button trigger modal -->
                <button class="btn btn-danger btn-raised btn-sm" href="" data-toggle="modal" data-target="#delete_employee{{ emp.id }}">
                    <i class="fa fa-times"></i> Delete
                </button>
                {% include 'employees/delete_employee_modal.html' %}
                  {% if emp.marital_status == 'Married' %}
                    <br>
                    <br>
                    <a href="{% url 'employees:all-relations' emp.id %}" class="btn btn-primary btn-raised btn-sm">
                        <i class="fa fa-users"></i> See Relations
                    </a>
                    <a href="{% url 'employees:add-relation' emp.id %}" class="btn btn-success btn-raised btn-sm">
                        <i class="fa fa-plus"></i> Add Relation
                    </a>
                  {% else %}
                      <br>
                      <br>
                      <p class="lead text-center">This employee is single</p>
                  {% endif %}
              {% endif %}
                  <br>
                  <br>
              </div>
            </div>
            </div>
        {% empty %}
            <p class="lead text-center">No employees yet</p>
        {% endfor %}
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

employee/templates/employees/all_employees_table.html
{% extends 'main_website/base.html' %}
{% block content %}
    <h2 class="text-center"><i class="fa fa-users"></i> {{ title }}</h2>
    <br>

    <table class="table table-striped">
        <thead>
          <tr>
            <th>Full Name</th>
            <th>Age</th>
            <th>Gender</th>
            <th>Place of Birth</th>
            <th>Position</th>
            <th>Job</th>
            <th>Marital Status</th>
            <th>Number of Relations</th>
            <th>Update</th>
            <th>Update Salary</th>
            <th>Delete</th>
            <th>See Relations</th>
            <th>Add Relation</th>
          </tr>
        </thead>
        <tbody>
        {% for emp in object_list %}
          <tr>
            <td><a href="{% url 'employees:detail' emp.id %}">{{ emp.full_name }}</a></td>
            <td>{{ emp.age }}</td>
            <td>{{ emp.gender }}</td>
            <td>{{ emp.place_of_birth }}</td>
            <td>{{ emp.position }}</td>
            <td>{{ emp.job }}</td>
            <td>{{ emp.marital_status }}</td>
            <td>{{ emp.relationship_set.all.count }}</td>
            {% if emp.freeze == True %}
              <td>
                  <span style="color: #f00; margin-top: 18px;">This employee is frozen</span>
              </td>
                <td></td>
                <td></td>
            {% else %}
            <td>
                <a href="{% url 'employees:update' emp.id %}" class="btn btn-info btn-raised btn-sm">
                    <i class="fa fa-user"></i> Update
                </a>
            </td>
            <td>
                <a href="{% url 'employees:update-salary' emp.id %}" class="btn btn-default btn-raised btn-sm">
                    <i class="fa fa-dollar-sign"></i>  Update Salary
                </a>
            </td>
            <td>
                <!-- Button trigger modal -->
                <button class="btn btn-danger btn-raised btn-sm" href="" data-toggle="modal" data-target="#delete_employee{{ emp.id }}">
                    <i class="fa fa-times"></i> Delete
                </button>
                {% include 'employees/delete_employee_modal.html' %}
            </td>
            {% endif %}
            {% if emp.marital_status == 'Married' %}
            <td>
                <a href="{% url 'employees:all-relations' emp.id %}" class="btn btn-primary btn-raised btn-sm">
                    <i class="fa fa-users"></i> See Relations
                </a>
            </td>
            <td>
                <a href="{% url 'employees:add-relation' emp.id %}" class="btn btn-success btn-raised btn-sm">
                    <i class="fa fa-plus"></i> Add Relation
                </a>
            </td>
            {% else %}
                <td>
                    <span>This employee is single</span>
                </td>
                <td></td>
            {% endif %}
          </tr>
        {% empty %}
            <p class="lead text-center">No employees yet</p>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

employee/templates/employees/all_relations.html
{% extends 'main_website/base.html' %}

{% block content %}
    <div class="row">
        <h2 class="text-center"><i class="fa fa-users"></i> {{ title }} For <a href="{% url 'employees:detail' id %}">{{ name }}</a></h2>
        <a href="{% url 'employees:add-relation' id %}" class="btn btn-success btn-raised" style="display: table; margin: 0 auto;">
            <i class="fa fa-plus"></i> Add Relation
        </a>
        <br>
        {% for emp in object_list %}
            <div class="col-sm-4">
            <div class="thumbnail">
              <div class="caption">
                <h4>Name : {{ emp.name }}</h4>
                <p>Relationship Type : {{ emp.relationship_type }}</p>
                <p>Age : {{ emp.age }}</p>
                <p>Date Of Birth : {{ emp.date_of_birth }}</p>
                <a href="{% url 'employees:update-relation' emp.id %}" class="btn btn-info">
                    <i class="fa fa-edit"></i> Update
                </a>
                <!-- Button trigger modal -->
                <button class="btn btn-danger" href="" data-toggle="modal" data-target="#delete_relation{{ emp.id }}">
                    <i class="fa fa-times"></i> Delete
                </button>
                {% include 'employees/delete_relation_modal.html' %}
              </div>
            </div>
            </div>
         {% empty %}
            <p class="lead text-center">This employee has no relations yet</p>
        {% endfor %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    </div>
{% endblock %}

employee/templates/employees/delete_employee_modal.html
<!-- Modal -->
<div class="modal fade" id="delete_employee{{ emp.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="border-radius: 6px;">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete Account</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top: -21px;">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete employee {{ emp.full_name }}?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form method="POST" action="{% url 'employees:delete' emp.id %}" style="display: inline-block;">
            {% csrf_token %}
            <a href="{% url 'employees:delete' emp.id %}">
                <button class="btn btn-danger">
                    Confirm Delete
                </button>
            </a>
        </form>
      </div>
    </div>
  </div>
</div>

employee/templates/employees/delete_relation_modal.html
<!-- Modal -->
<div class="modal fade" id="delete_relation{{ emp.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="border-radius: 6px;">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete Account</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top: -21px;">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete relation {{ emp.name }}?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form method="POST" action="{% url 'employees:delete-relation' emp.id %}" style="display: inline-block;">
            {% csrf_token %}
            <a href="{% url 'employees:delete-relation' emp.id %}">
                <button class="btn btn-danger">
                    Confirm Delete
                </button>
            </a>
        </form>
      </div>
    </div>
  </div>
</div>

employee/templates/employees/employee_detail.html
{% extends 'main_website/base.html' %}

{% load mathfilters %}

{% block content %}
    <div class="container">
        <div class="row">
            <h2 class="text-center"><i class="fa fa-user"></i> {{ object.full_name }} CV.</h2>
            <br>
            <div class="col-sm-6">
                <br>
                <p class="lead"><b>Full Name : </b>{{ object.full_name }}</p>
                <p class="lead"><b>First Name : </b>{{ object.first_name }}</p>
                <p class="lead"><b>Middle Name : </b>{{ object.middle_name }}</p>
                <p class="lead"><b>Last Name : </b>{{ object.last_name }}</p>
                <p class="lead"><b>Age : </b>{{ object.age }}</p>
                <p class="lead"><b>National Identifier : </b>{{ object.national_identifier }}</p>
                <p class="lead"><b>Gender : </b>{{ object.gender }}</p>
                <p class="lead"><b>Date Of Birth : </b>{{ object.date_of_birth }}</p>
                <p class="lead"><b>Place Of Birth : </b>{{ object.place_of_birth }}</p>
                <p class="lead"><b>Position : </b>{{ object.position }}</p>
                <p class="lead"><b>Earning Description  : </b>{{ object.earning_description | linebreaks }}</p>
            </div>
            <div class="col-sm-6">
                <br>
                <p class="lead"><b>Job : </b>{{ object.job }}</p>
                <p class="lead"><b>Country : </b>{{ object.country }}</p>
                <p class="lead"><b>Nationality : </b>{{ object.nationality }}</p>
                <p class="lead"><b>Marital Status : </b>{{ object.marital_status }}</p>
                <p class="lead"><b>Joined In : </b>{{ object.added | timesince}} ago.</p>
                <p class="lead"><b>profile update date : </b>{{ object.updated | timesince}} ago.</p>
                <p class="lead"><b>Main Salary : </b>{{ object.salary }}</p>
                <p class="lead"><b>Earning : </b>{{ object.earning }}</p>
                <p class="lead"><b>Deduction : </b>{{ object.deduction }}</p>
                <p class="lead"><b>Net Salary : </b>{{ object.salary |add:object.earning |sub:object.deduction }}</p>
                <p class="lead"><b>Deduction Description : </b>{{ object.deduction_description | linebreaks }}</p>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

employee/templates/employees/employee_update.html
{% extends 'main_website/base.html' %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}

{% block content %}
    <div class="col-sm-offset-3 col-sm-6">
        <h2 class="text-center"><i class="fa fa-user"></i> {{ title }} <a href="{% url 'employees:detail' object.id %}">{{ object.full_name }}</a></h2>
        <br>
            {#{% if form.errors.non_field_errors %}#}
            {#    {{ form.errors.non_field_errors }}#}
            {#{% endif %}#}

            {#{% if form.errors %}#}
            {#    {{ form.errors }}#}
            {#{% endif %}#}

            {% load crispy_forms_tags %}

            <form method="POST" enctype="multipart/form-data" action="" class="form-group">
                {% csrf_token %}
            {#    {% crispy form %}#}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">{{ title }}</button>
            </form>

            {#{% if form.instance %}#}
            {#    <h1>{{ form.instance }}</h1>#}
            {#{% endif %}#}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    </div>
{% endblock %}

employee/templates/employees/update_employee_salary.html
{% extends 'main_website/base.html' %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}

{% block content %}
    <div class="col-sm-offset-3 col-sm-6">
        <h2 class="text-center"><i class="fa fa-user"></i> {{ title }} For <a href="{% url 'employees:detail' id %}">{{ name }}</a></h2>
        <br>
            {#{% if form.errors.non_field_errors %}#}
            {#    {{ form.errors.non_field_errors }}#}
            {#{% endif %}#}

            {#{% if form.errors %}#}
            {#    {{ form.errors }}#}
            {#{% endif %}#}

            {% load crispy_forms_tags %}

            <form method="POST" enctype="multipart/form-data" action="" class="form-group">
                {% csrf_token %}
            {#    {% crispy form %}#}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">{{ title }}</button>
            </form>

            {#{% if form.instance %}#}
            {#    <h1>{{ form.instance }}</h1>#}
            {#{% endif %}#}

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    </div>
{% endblock %}

employee/templates/employees/update_relation.html
{% extends 'main_website/base.html' %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}

{% block content %}
    <div class="col-sm-offset-3 col-sm-6">
        <h2 class="text-center"><i class="fa fa-user"></i> {{ title }}</h2>
        <br>
            {#{% if form.errors.non_field_errors %}#}
            {#    {{ form.errors.non_field_errors }}#}
            {#{% endif %}#}

            {#{% if form.errors %}#}
            {#    {{ form.errors }}#}
            {#{% endif %}#}

            {% load crispy_forms_tags %}

            <form method="POST" enctype="multipart/form-data" action="" class="form-group">
                {% csrf_token %}
            {#    {% crispy form %}#}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">{{ title }}</button>
            </form>

            {#{% if form.instance %}#}
            {#    <h1>{{ form.instance }}</h1>#}
            {#{% endif %}#}

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    </div>
{% endblock %}